GET http://localhost:3001/api
###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/6a310233f5a902035314fdb9
###
GET http://localhost:3001/api/persons/6a310225f5a902035314fdb8
###
GET http://localhost:3001/api/persons/6a3001b95d5a94663584e259

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "David Nguyen",
    "number": "0987-2212-3321"
}

###
DELETE http://localhost:3001/api/persons/6a3001b95d5a94663584e259